name: car_advisor
services:
  postgres:
    image: postgres:17.2
    shm_size: 128mb
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

volumes:
  postgres_data:
