# Generated by Django 5.1.5 on 2025-02-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_advisor_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
