# Generated by Django 5.1.5 on 2025-02-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_advisor_api', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_advisor_api.brand')),
            ],
        ),
    ]
