# Generated by Django 5.1.5 on 2025-02-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_advisor_api', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('referred_price_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferredBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_advisor_api.brand')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_advisor_api.user')),
            ],
        ),
    ]
